stages:
  - lint
  - test

variables:
  POSTGRES_USER: 'apps'
  POSTGRES_PASSWORD: ''
  POSTGRES_DB: 'test_apps'
  POSTGRES_HOST_AUTH_METHOD: trust

flake8:
  stage: lint
  image: python:3.7-alpine
  before_script:
    - pip install -q flake8
  script:
    - flake8

pytest:
  stage: test
  image: python:3.7

  tags:
    - python
  services:
    - postgres:11
  variables:
    DATABASE_URL: pgsql://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB

  before_script:
    - pip install -r requirements/local.txt

  script:
    - pytest

